const ordersTypes = {
  SAVE_ORDER_HISTORY_START: "SAVE_ORDER_HISTORY_START",
  GET_USER_ORDER_HISTORY_START: "GET_USER_ORDER_HISTORY_START",
  SET_USER_ORDER_HISTORY_START: "SET_USER_ORDER_HISTORY_START",
  GET_CLIENT_ORDER_HISTORY_START: "GET_CLIENT_ORDER_HISTORY_START",
  SET_CLIENT_ORDER_HISTORY_START: "SET_CLIENT_ORDER_HISTORY_START",
  GET_ORDER_DETAILS_START: "GET_ORDER_DETAILS_START",
  SET_ORDER_DETAILS: "SET_ORDER_DETAILS",
  SET_ORDER_COMPLETE: "SET_ORDER_COMPLETE",
};

export default ordersTypes;
